version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build finito
artifacts:
  files:
    - build/**/*
