version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo work already
  pre_build:
    commands:
      - echo install npm
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build finito
artifacts:
  files:
    - build/**/*
    - appspec.yml
